### ISSUE TITLE
Option to hide dock icon on macOS

### ISSUE THREAD

**Issue by CatsLover2006** [samuelthomas2774/nxapi#18]
Self-explanitory, you can do this manually by changing a file in info.plist in the compiled application, but I'd like an option to do this.

**Comment by samuelthomas2774** [comment]
I don't really notice it because I usually have so much apps open anyway, but I like this idea. I think maybe it should be visible if any windows are open and hidden otherwise, like Keybase? As the app doesn't need to be visible at all times for Discord presence/friend notifications but the UI isn't just like a preferences window either.

**Comment by samuelthomas2774** [comment]
Added in [v1.4.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.4.0) (https://github.com/samuelthomas2774/nxapi/commit/ce6272318ec29b02fd6cf37945ac6cf9df40a653).

Now I just need an actual icon for when there are windows open. :smile:
