### ISSUE TITLE
Opening on startup

### ISSUE THREAD

**Issue by JulesSorensen** [samuelthomas2774/nxapi#19]
Hello, I have a small suggestion to share
Adding a window with general settings could be nice, it could list various options such as launching the application at system startup (in background or not) for example

**Comment by samuelthomas2774** [comment]
Electron has an API to do this but only for macOS and Windows, and for launching in the background, only macOS. So I can do this, just it won't work exactly the same on all platforms. (https://www.electronjs.org/docs/latest/api/app#appgetloginitemsettingsoptions-macos-windows)

So far I've avoided adding a preferences window just to make the app a bit simpler, but a separate preferences window would also probably be a better place to have Discord presence options than the Discord setup window because of how this is setup internally...

- https://github.com/samuelthomas2774/nxapi/issues/13

Another thing would be an option to have the app prevent sleep. I don't think it's a huge issue but having an option to prevent sleep only while Discord presence is active would be nice. I know one NSO-RPC user has had an issue with this (https://github.com/MCMi460/NSO-RPC/issues/28).

**Comment by samuelthomas2774** [comment]
Just an update on this: I've added a preferences window with startup options for macOS and Windows, and all the current additional options for Discord presence. This will be available in the next release.

<img width="692" alt="Screenshot 2022-09-12 at 17 00 52" src="https://user-images.githubusercontent.com/8474065/189702295-032036f1-8233-4c68-b13c-b6e21507055f.png">

(cc. @Velegand)

**Comment by JulesSorensen** [comment]
Awesome, this is perfect thank you!

**Comment by samuelthomas2774** [comment]
Added in [v1.5.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.5.0).

**Comment by Velegand** [comment]
Is 'Open in background' coming to Windows?

**Comment by VincentJoshuaET** [comment]
I cannot seem to check 'Open in background' on macOS Ventura.
