### ISSUE TITLE
splatoon 3 app missing in context menu

### ISSUE THREAD

**Issue by oscie57** [samuelthomas2774/nxapi#21]
![image](https://user-images.githubusercontent.com/66192059/189505394-0d40bc60-0f94-4f99-a4d8-3355959495c0.png)
splatoon 3 is not here

**Comment by samuelthomas2774** [comment]
Those are hardcoded in the app instead of being retrieved from Nintendo's API - I never did this properly so the app doesn't need to authenticate to all accounts immediately when it's opened. The proper solution is to cache web services when they're fetched and use those, I just haven't gotten around to doing it yet (at the time I added the menu the rest of the app didn't exist, so web services were never fetched until authentication is triggered by doing something in the menu). :smile:

As a workaround it can still be launched though the main window for now. The next update will add proper support for SplatNet 3, including launching it from the menu, plus SplatNet 3 features for the command line and JS library.

**Comment by oscie57** [comment]
i've found where it's set, though i dont know what information is needed for it. if i did, i'd make a pull request.
https://github.com/samuelthomas2774/nxapi/blob/eaa0c0810e1eefdcaa02c1e2a235d7da4d5b3323/src/app/main/menu.ts#L122

**Comment by samuelthomas2774** [comment]
From https://github.com/samuelthomas2774/nxapi/commit/07a30e89be637734e3db25339fe6bb377094a5ef the list used here is fetched from Nintendo, so it'll always be up to date if Nintendo adds or updates and game web services.
