### ISSUE TITLE
windows scroll bar hell

### ISSUE THREAD

**Issue by oscie57** [samuelthomas2774/nxapi#24]
i put this on the discord but i thought it'd be a good idea to put it here to make tracking of this issue easier.

on windows, game-specific services have alot of scrollbars that look super ugly in use, for example:
![image](https://user-images.githubusercontent.com/66192059/190881245-28c6ae94-9b54-41db-a731-6457d2061907.png)

as mentioned by two people, using css would probably make it look alot better.

---

also a slight suggestion, would hiding the "file, edit, etc" bar be a possibility? it seems quite unnecessary to be there if im honest, and removing it shouldnt be too much of a hassle.

**Comment by samuelthomas2774** [comment]
I've had a look at the scrollers in SplatNet 3 and have hidden some of them. This could easily break but it shouldn't make the app unusable (just the extra scrollbars will reappear), which is why I wasn't sure it would be possible to do this safely. (I think there might still be some pages where additional scroll bars are visible, for example I haven't touched any scrollers with pull-to-refresh in case changing the scrolling options could break that.)

<img width="487" alt="Screenshot 2022-09-20 at 21 00 58" src="https://user-images.githubusercontent.com/8474065/191353377-826a274f-f34a-453e-a9e5-2e8676930c27.png">

I've hidden the menu bar as well, thanks for reminding me again.

**Comment by oscie57** [comment]
oh awesome!

**Comment by samuelthomas2774** [comment]
Added in [v1.5.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.5.0).

**Comment by oscie57** [comment]
it is still in some places

![image](https://user-images.githubusercontent.com/66192059/198857110-2fa4cc69-1d95-4c06-89e7-2f2cf212d40c.png)
![image](https://user-images.githubusercontent.com/66192059/198857112-f9422a07-5c7d-4509-9a02-2391bd47f2fb.png)

**Comment by samuelthomas2774** [comment]
A few pages (such as those ones) have nested sliding/pull-to-refresh scrollers; I haven't changed those intentionally just in case it affects anything to do with that functionality (or in an update).

**Comment by oscie57** [comment]
could you make them less intrusive?

**Comment by oscie57** [comment]
did you see this? unsure what the lack of response means lmao

**Comment by samuelthomas2774** [comment]
The scroll bars can be themed (https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) but I'd prefer to just keep the native ones for now as that replaces them entirely.
