### ISSUE TITLE
Error: [splatnet3] GraphQL error: PersistedQueryNotFound

### ISSUE THREAD

**Issue by spikeyscout** [samuelthomas2774/nxapi#39]
Getting this error everytime i load up Splatoon on my switch, and my Discord status no longer shows the enhanced Rich Presence data for Splatoon 3. Just started popping up after working for a while.
![image](https://user-images.githubusercontent.com/34626346/207182760-6a0a56ed-614e-4b9f-9c46-cd0cf4fd9ab9.png)

**Comment by samuelthomas2774** [comment]
Nintendo stopped accepting requests for queries used in versions of SplatNet 3 before 2.0.0 last week (including some used for Splatoon 3 presence in nxapi v1.5.0):

- https://github.com/samuelthomas2774/nxapi/discussions/11#discussioncomment-4351724

This will be fixed in the next release (soon). (This will also make it possible for SplatNet 3 queries to be updated without updating nxapi.)

**Comment by spikeyscout** [comment]
yup, got the newest version linked in discord and its working, thank you so much for the work you do!
