### ISSUE TITLE
Error everytime i try and log in with my nintendo account

### ISSUE THREAD

**Issue by SucksAtstuff** [samuelthomas2774/nxapi#7]
everytime i try and add my user by logging in after ive logged in i get this ![image_2022-06-28_001251990](https://user-images.githubusercontent.com/75032354/176044434-189e9bbe-dcfb-4a8b-80c4-c28246be00cf.png)
 but i get an email that a new login has been detected

**Comment by samuelthomas2774** [comment]
I don't really know what could be causing an issue during this stage of logging into a Nintendo Account as it's pretty much just handing over to Nintendo as part of a standard OAuth 2.0/OpenID Connect authorisation. As you get an email I guess the login was successful, so the error must be at the authorisation/user consent stage.

Are you able to login to your Nintendo Account and the Nintendo Switch Online app normally?

**Comment by SucksAtstuff** [comment]
Yes i am able to log in on my switch since i did it yesterday cuz  it signed me out and when i click the logo it waits a bit then goes back to sign in

**Comment by samuelthomas2774** [comment]
> Yes i am able to log in on my switch

I mean in the Nintendo Switch Online app on a phone.

> when i click the logo it waits a bit then goes back to sign in

That would indicate the login actually wasn't successful. :shrug: Or, it logs out because of the error.

---

I don't know what else to suggest as I can't reproduce this issue, but you could either:

- Maybe try signing in using an external account (Google, Apple ID, etc) if you have one linked to your Nintendo Account?
- Or, try signing in using the command line (you'll still be able to use the app after). To do this:
    1. [Install Node.js](https://nodejs.org/en/) if you don't have it installed already. (You'll need to logout and log back into Windows after doing this.)
    2. Open a command prompt and run `npm install --global nxapi`.
    3. Then run `nxapi nso auth`. This should guide you through logging in using a browser.

**Comment by SucksAtstuff** [comment]
usin cmd worked thanks :)
