### ISSUE TITLE
Do you have Nintendo Switch Online API for user games and playtime?

### ISSUE THREAD

**Issue by BoBoGithub** [samuelthomas2774/nxapi#8]
I want some apis for user games and playtime,

The Nintendo Switch Parental Controls App has the apis, but this app require user must Link Device.

Can you help me?

**Comment by samuelthomas2774** [comment]
Unfortunately Coral (the Nintendo Switch Online app/its API) doesn't expose your full play log. The only way to access this is using a Nintendo Switch console.

<details open><summary>Further information</summary>

Play activity is recorded in a few different places:

- Your play activity/log, which you can optionally make available to friends/best friends/everyone. This includes (for each title) the number of times was launched, total play time in minutes and first/last played timestamp. This is linked to your Nintendo Switch network account (which is why this is only recorded once a Nintendo Account is linked), and is only available via [the Nintendo Switch accounts server (BAAS)](https://github.com/kinnay/NintendoClients/wiki/BAAS-Server).
- Moon (aka. the Nintendo Switch Parental Controls app/API), which records the total play time (extremely annoyingly) rounded down to *300 seconds* (5 minutes) per user/day, and the first played date.
- [Consoles must record this information locally as well, in much more detail (like 3DS/Wii U) and for each user, but separate to the play activity?](https://github.com/tallbl0nde/NX-Activity-Log) Maybe Nintendo just copied this from the 3DS/Wii U exactly as it is, then it gets synced to your play activity later?

</details>

**Comment by BoBoGithub** [comment]
Hello, @samuelthomas2774

Recently I found that the “My Nintendo“ App contains the user's game information and game duration. 

Can you extract the Api related to the game duration in this package?

**Comment by samuelthomas2774** [comment]
I did have a look the the My Nintendo app a while ago. It uses a few different APIs for news, play history, etc. All Nintendo Accounts are able to authenticate to all services and everything generally works fine, however the play history is empty for non-JP accounts. If this changes I'll definitely add support for the My Page (play history, My Nintendo points) API but for now I'm just focusing on the SplatNet 3 API.

**Comment by hb-robo** [comment]
> All Nintendo Accounts are able to authenticate to all services and everything generally works fine, however the play history is empty for non-JP accounts. If this changes I'll definitely add support for the My Page (play history, My Nintendo points) API but for now I'm just focusing on the SplatNet 3 API.

Hi there, sorry to necro this issue, but I was wondering if anything had changed on this front since this was closed.
