### ISSUE TITLE
User agent format when connecting to s2s API

### ISSUE THREAD

**Issue by frozenpandaman** [samuelthomas2774/nxapi#9]
Can you help me figure out why the "version" part of many of the user agents coming from your application here seem to be randomly generated numbers? This isn't what I'd expect to see or how stuff should be set up.

![image](https://user-images.githubusercontent.com/7245874/177575317-7c034333-78aa-4046-9583-82232a5933cb.png)

Thanks!

**Comment by frozenpandaman** [comment]
@samuelthomas2774 The earliest instance of it was 2022-07-06 07:27:19 UTC, so just very recently. Recent logs show a mix of users making requests I'd estimate 1/3 of the time with `nxapi/0.2` and 2/3 of the time with the `nxapi/weird.numbers` user agent. I'm guessing "1.2.0" isn't getting treated as a string or something and as a result is messing up??

(Also an aside but jeez, you have a lot of users, just saying lol… doesn't look like it's just a couple haywire clients as has sometimes happened before with other projects using the API… now s2s  users keep getting the "too many requests" error so I had to increase the # of global requests allowed per minute from 4 to 10 just now.)

**Comment by samuelthomas2774** [comment]
Just tested the release build of the app straight from GitHub, and also with some debug logs and it all seems to be sending properly formed user agents...

<img width="933" alt="Screenshot 2022-07-06 at 16 09 14" src="https://user-images.githubusercontent.com/8474065/177583599-b9805310-543f-4b51-b413-b5480243b4b3.png">

That should be sent from 78.32.231.153/2001:470:6d29:51:5472:173:9b2a:564e/2001:470:6d29:57:346c:b76d:9f81:3d1b (screenshot timestamp was 15:09:14 UTC).

Are you seeing any other versions reported? 0.2.0 is quite old now (and I didn't release that until I added an update check), plus there should be quite a few other versions between 0.2.0 and 1.2.0. I'll check older versions as well just in case it's any of those. I don't know why this would only be appearing today though, even if it is to do with the new format in 1.2.0, as that was released Saturday.

Sorry about this, those user agents are obviously very wrong so please do block them if it's causing issues.

**Comment by frozenpandaman** [comment]
>The earliest instance of it was 2022-07-06 07:27:19 UTC, so just very recently.

My bad, @samuelthomas2774, I was wrong about this. The earliest instance looks like it was:
```
"xxx.xxx.xxx.xxx", "2022-07-05 06:55:43", "nxapi/0.7.972239190788646", 200, "OK"
```

They started immediately after that – like, various different ones from multiple IPs, all starting that exact minute.

**Comment by samuelthomas2774** [comment]
> Also an aside but jeez, you have a lot of users, just saying lol…

I'm not sure I do... GitHub doesn't show download stats for release asset downloads, but according to the repository traffic stats (from I think the last two weeks?) there's only been 5 unique visitors to the releases page, so if these are legitimate nxapi users they didn't download the app from here. [npm download stats](https://www.npmjs.com/package/nxapi?activeTab=versions) (cli-only/library use) are a bit higher but I think that includes lots of bots (e.g. for malware/vulnerability scanning?). I'd like to have my own analytics for actual app use but I also don't really want to be collecting anything, plus that doesn't really work as nxapi is at it's core just a library for the API stuff (the CLI and Electron app are just built on top of it).

Of course ideally I wouldn't be sending you/NexusMine anything as well, then this wouldn't ever be a problem. I'm still trying to figure out how `gen_audio_h`/`gen_audio_h2` works (as in, looking at the code and pretending I might know what any of it means lol). I'm thinking it would be great to have a WebAssembly binary that (somehow?) calls the function, then we're not really sharing how it works and could still tie it to an API to stop Nintendo complaining, and prevent sending invalid tokens.

> FWIW there are older logs, e.g. from June where I see 1.1.0 and 0.3.0 (and 0.3… which is different?) showing up, and a couple 1.0.0s.

`0.3` on it's own isn't right... The version number comes from the package.json version field so should always be exactly one of these: https://www.npmjs.com/package/nxapi?activeTab=versions. (And pre-1.0.0 there's no Electron app so they should all be from npm.) The other versions sound right though.

---

For the Electron app, because it can launch game-specific services there should be slightly more requests per user than anything else, as those tokens can't really be cached regardless of how long they're valid for, but even then that's only when they're opened.

The number of downloads I can see certainly doesn't match up with the request volume you're getting, so I have no idea where those requests are coming from.

Sorry this is taking up some of your holiday. If you want to send me some logs I'll have a look and see if I can figure out what this is, but comparing my download stats with the number of users I can see from just the partial IP addresses in the screenshot (plus having no idea how these user agents could be generated) I'm not sure these actually are nxapi users (but then I don't know why they'd be fake either). It might be worth having a look at the IP addresses, as e.g. they shouldn't be Tor or other proxies because nxapi uses node-fetch which by default can't use a proxy.

**Comment by samuelthomas2774** [comment]
I've tested some older versions (with added debug logs) and they're all sending correct user agents.

<details><summary>1.2.0 app, Windows 10, GitHub Releases</summary>

```
nxapi/1.2.0 (node 16.14.2; win32 10.0.19043) nxapi-app (Chromium 102.0.5005.61; Electron 19.0.1)
```

![Screenshot 2022-07-07 161541](https://user-images.githubusercontent.com/8474065/177821076-a7ae4e29-16aa-4a93-a107-deea4fb75ca4.png)

</details>

<details><summary>1.1.0 app, Windows 10, GitHub Releases</summary>

```
nxapi/1.1.0
```

![Screenshot 2022-07-07 162214](https://user-images.githubusercontent.com/8474065/177821397-c6f67641-2fc6-4b66-aa51-7131412d072d.png)

</details>

<details><summary>0.3.0 cli, Windows 10, npm registry</summary>

```
nxapi/0.3.0
```

![Screenshot 2022-07-07 162914](https://user-images.githubusercontent.com/8474065/177821610-1a4f8cc4-42e4-454a-8df6-dca924f54330.png)

</details>

<details><summary>1.2.0 cli, Windows 10, npm registry</summary>

```
nxapi/1.2.0 (node 16.15.0; win32 10.0.19043) nxapi-cli
```

![Screenshot 2022-07-07 163316](https://user-images.githubusercontent.com/8474065/177821773-9a970b90-fbfc-4f38-bb71-e6195014c797.png)

</details>

They should show up in your logs between 15:15-15:33 UTC from 78.32.231.153/2001:470:6d29:51:f108:ec21:54a3:404b/2001:470:6d29:57:f108:ec21:54a3:404b (there should be 5 requests, I forgot to edit one version to log the user agent).

I'm very sure now there's no way those user agents could actually be generated by nxapi. Even if used as a library, the user agent will always start with `nxapi/1.2.0 (...)` (or end with `nxapi/version` before 1.2.0), dependents can only append to it (or nxapi prints a warning if they don't).

> Looks like it is actually only three users over and over sending the 0.2 user agent strings

I was going to test 0.2.0 but tested 0.3.0 instead because it changes the `X-ProductVersion` header from `2.0.0` to `2.1.1`. `2.0.0` is now being rejected by Nintendo, so those clients will never work now. nxapi itself doesn't retry anything automatically (except once after the token expires) so I don't know why they keep sending requests.

**Comment by samuelthomas2774** [comment]
Hi @frozenpandaman, are you still getting these randomised requests to your API? Still really confused by this :confused:.

**Comment by samuelthomas2774** [comment]
Hi @frozenpandaman, is this still an issue?

Since v1.3.0 nxapi will refuse to authenticate (and thus possibly contact your API) more than 4 times per hour (https://github.com/samuelthomas2774/nxapi/commit/e12bb364a7b46907eefd11d0ecc84b1a645de9cc), and will also append `unidentified-script` to the user agent if it detects it's not running in a terminal (no TTY). Also nxapi now contacts my server to check certain settings (mainly version numbers to report to Nintendo, although there's also the ability for me to remotely disable using certain APIs including yours if necessary); from that I can see (in the last day) nxapi was used by at least 12 users, including myself.

**Comment by frozenpandaman** [comment]
@samuelthomas2774 Sorry for the late reply! Thanks so much for all your help here. I just checked the logs and the version numbers seem to now be working correctly. I'm seeing recent requests from versions 1.3.0 and 0.2 which is fine by me.

Thanks for the other updates as well, will be keeping my eye on that other discussion & I joined the server!

**Comment by samuelthomas2774** [comment]
Thanks for checking, it's good to hear that whatever was causing this is resolved now. `0.2` shouldn't be sent from nxapi but as long as it's not causing any issues...

I've seen that you've just switched to @JoneWang's imink API in splatnet2statink; I'll switch the default in nxapi to imink as well then, as the imink API seems to be more stable than flapg. I'll leave the option to use s2s+flapg until you shut down your API.
